### ISSUE TITLE
after resedit executable binary file made by pkg.js, got "Pkg: Error reading from file." error when execute the saved exe

### ISSUE THREAD

**Issue by lling1105** [jet2jet/resedit-js#21] opened 2021-06-21 07:27 UTC
codes
```js
const ResEdit = require('resedit');
const fs = require('fs');
let package = require('./package.json');
let data = fs.readFileSync('./build/web-automation.exe');
let exe = ResEdit.NtExecutable.from(data);
let res = ResEdit.NtExecutableResource.from(exe);
// -- replace version
let viList = ResEdit.Resource.VersionInfo.fromEntries(res.entries);
let vi = viList[0];
let versions = package.version.split('.');
// vi.fixedInfo.fileVersionMS = 0x40004; // '1.1'
vi.fixedInfo.fileVersionLS = 0;
vi.setStringValues(
    { lang: 1033, codepage: 1200 },
    {
        FileVersion: '1.1',
        FileDescription: `${package.version}`,
        ProductName: '小花'
    }
);

vi.outputToResourceEntries(res.entries);


// write to another binary
res.outputResource(exe);
let newBinary = exe.generate();
fs.writeFileSync('./build/web-automation.exe', Buffer.from(newBinary));
```

**Comment by jet2jet** [comment] 2021-06-21 10:34
Thanks for the report.  
Unfortunately, I could not reproduce the problem with the code you provided.  
(I tried with the file `main.js` with code `console.log('Hello, world')`, and with the command line `pkg -t node14-win-x64 main.js`)

If you could, please provide the minimum project that you reproduce the problem.

**Comment by CWHON** [comment] 2021-07-06 01:41
@jet2jet I have created a demo project to reproduce the issue: https://gist.github.com/CWHON/8ecc5e5940638e5d221e4ffadfe29f7a

When running the original exe, the application generates the following output:
`Starting application...`

When running the edited exe, the application generates the following output:
`Pkg: Error reading from file.`

**Comment by jet2jet** [comment] 2021-07-06 09:10
Very thanks for the repro sources.

I found that the problem is changing location (address) of embedded source code data.
The source code data is attached as 'extra data', and, according to the spec, its location should be 'the last of binary'. (the weird executable still contains the extra data correctly.) This location may change for example when the resource data size changes (i.e. the entire binary size changes).
But `pkg` uses a 'fixed' location to refer to the source code data (this is not a bug), so if the location is changed, the source code data will not work correctly.

This is a slightly complex problem because both `pkg` and resedit-js worked as expected, but I think resedit-js can provide a new option not to change resource size to keep 'extra data' location.
I'll work for it.

**Comment by jet2jet** [comment] 2021-07-06 11:07
I published resedit@1.1.0 and resedit-cli@1.1.0 to solve this problem.
Please specify `-N` (`--no-grow`) option to resedit-cli tool to avoid changing resource size unexpectedly.

**Comment by CWHON** [comment] 2021-07-07 01:51
Thanks @jet2jet for the quick fix. I can confirm the basic repro project is now working with the latest resedit-cli.

Side note - the argument `-N` works but not `--no-grow' - throws "ERROR: Unknown argument: grow".

**Comment by jet2jet** [comment] 2021-07-07 11:34
> Side note - the argument -N works but not `--no-grow' - throws "ERROR: Unknown argument: grow".

I fixed as resedit-cli@1.1.1.
Thanks for the confirmation.

**Comment by Lucifer2033** [comment] 2021-07-10 01:53
I have a problem after changing the icon, the executable file does not start

**Comment by jet2jet** [comment] 2021-07-11 01:11
> I have a problem after changing the icon, the executable file does not start

Please provide reproduction code or more details (repro. steps, etc.)

**Comment by Lucifer2033** [comment] 2021-07-12 02:23
```
const ResEdit = require('resedit');
const fs = require('fs');
let data = fs.readFileSync('./MyApp.exe');
let exe = ResEdit.NtExecutable.from(data);
let res = ResEdit.NtExecutableResource.from(exe);
let iconFile = ResEdit.Data.IconFile.from(fs.readFileSync('iconset.ico'));

ResEdit.Resource.IconGroupEntry.replaceIconsForResource(
  // destEntries
  res.entries,
  // iconGroupID
  101,
  // lang ('lang: 1033' means 'en-US')
  1033,
  // icons (map IconFileItem to IconItem/RawIconItem)
  iconFile.icons.map((item) => item.data)
);
// -- replace version
let viList = ResEdit.Resource.VersionInfo.fromEntries(res.entries);
let vi = viList[0];
// vi.fixedInfo.fileVersionMS = 0x10001; // '1.1'
vi.fixedInfo.fileVersionLS = 0;
vi.setStringValues(
    { lang: 1049, codepage: 1200 },
    {
        FileVersion: '1.1',
        FileDescription: `test`,
        ProductName: 'test'
    }
);

vi.outputToResourceEntries(res.entries);


// write to another binary
res.outputResource(exe);
let newBinary = exe.generate();
fs.writeFileSync('./MyAppEdit.exe', Buffer.from(newBinary));
```

**Comment by jet2jet** [comment] 2021-07-12 10:57
> edit: I checked right now and the icon changed and everything works
> I created an ico in size yesterday and did not check it

ok, thanks anyway.
If you encountered a problem again, please try `outputResource`'s `noGrow` parameter (it might help you avoid the problem).

**Comment by jet2jet** [comment] 2021-08-16 07:50
Closing this issue. Feel free to reopen if some problems still persist.

**Closed by jet2jet** 2021-08-16 07:50 UTC
